backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/images"

collections:
  - name: "photos"
    label: "Blog Photos"
    folder: "content/photos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Year", name: "year", widget: "string" }
       - { label: "Region", name: "region", widget: "select", options: [{ label: "Virginia", value: "virginia" }, { label: "Maryland", value: "maryland" }, { label: "DC", value: "dc" }, { label: "Florida", value: "florida" }, { label: "Pennsylvania", value: "pennsylvania" }, { label: "West Virginia", value: "west-virginia" }, { label: "Portugal", value: "portugal" }, { label: "New York", value: "new-york" }, { label: "Illinois", value: "illinois" }, { label: "California", value: "california" }, { label: "France", value: "france" }, { label: "Italy", value: "italy" }, { label: "Hungary", value: "hungary" }, { label: "Canada", value: "canada" }, { label: "Massachusetts", value: "massachusetts" }, { label: "Tennessee", value: "tennessee" }, { label: "Connecticut", value: "connecticut" }, { label: "Other", value: "other" }] }